# Generated by Django 3.2.10 on 2022-02-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_walletid_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owned_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallets.walletid'),
        ),
    ]
