# Generated by Django 3.2.10 on 2022-02-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_wallet_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallets.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owned_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallets.walletid'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallets.wallet'),
        ),
    ]
