# Generated by Django 3.2.10 on 2022-02-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20220207_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
