# Generated by Django 3.2.10 on 2022-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_auto_20220207_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
